### PR TITLE
Revert "Revert "Add managed field""

### PR DESCRIPTION
**Pull request by benwhitis**
Reverts jamf/mut#119

We are learning how to GitHub

### CODE REVIEW

**Review by chrisgzim — APPROVED** [review]
contains the changes for xmlbuilder for "Managed" and the new Build version

**Comment by cdenesha** [comment]
lol 
Please expand the scope for #110 (and #s 116 and 119?) to mobile devices as well. I have to actually edit and update a script for this, on a somewhat regular basis. 
thank you,
chris

**Comment by chrisgzim** [comment]
hey @cdenesha! thank you for the feedback, just wanting to confirm something here: 

are you wanting to just change the field in the inventory record to "false" or is the end goal to send out "unmanage" commands to mobile devices?

**Comment by cdenesha** [comment]
I just need to mark them unmanaged, so the former.

**Pull request merged**
