### PR TITLE
Creds in keychain

### PR DESCRIPTION
**Pull request by mikelevenick**
Expected behavior:

- If "remember me" checkbox is checked, credentials will be stored in keychain as `com.jamf.mut.credentials` on a successful login. 
- If invalid credentials are supplied or login is unsuccessful, they will not be saved
- If there is a password change, the new password will overwrite the old in keychain (effectively, each time credentials are saved, the old credentials are deleted first (Keychain helper line 20))
- If the remember me checkbox is unchecked, any stored credentials are deleted when a login is attempted--regardless of whether or not it is successful.
- Logs relevant information based on what its doing
- Displays different messages depending if invalid login is from keychain info or entered info
- Deletes keychain info if keychain info led to invalid login

### CODE REVIEW

**Comment by benwhitis** [comment]
Checking this out.

**Review by benwhitis — COMMENTED** [review]
I am reviewing these changes now

**Comment by chrisgzim** [comment]
Checking this out

**Review by benwhitis — APPROVED** [review]
Tested User, Device, Computer updates. 

Verified Keychain item is added. 

Approving as it is working as intended

**Review by benwhitis — APPROVED** [review]
Approving again.

**Pull request merged**
